import NavBar from "@/components/NavBar";
import { Layout } from "antd";
import type { Metadata } from "next";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

export const metadata: Metadata = {
  title: "Cutdown",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.webp" type="image/x-icon" />
      </head>
      <body style={{ margin: 0, padding: 0 }}>
        <Layout className="layout">
          <NavBar />
          <main style={{ padding: 10 }}>{children}</main>
        </Layout>
      </body>
    </html>
  );
}
